from . import test_crm_account_opening_stages
from . import test_crm_account_opening_enquiry_fields
from . import test_crm_account_opening_stage_advance
from . import test_crm_account_opening_kycms
from . import test_crm_account_opening_aos
from . import test_crm_account_opening_manual_lost
from . import test_crm_account_opening_default_stage
from . import test_crm_account_opening_logging
from . import test_crm_account_opening_field_protection
