from . import test_crm_lead_partner_sync
from . import test_crm_lead_fields
from . import test_crm_lead_title
from . import test_crm_lead_source_medium
from . import test_crm_lead_conditional_mandatory
from . import test_crm_lead_duplicate_detection
from . import test_crm_lead_auto_assignment
from . import test_crm_lead_transfer
from . import test_crm_lead_transfer_wizard
from . import test_crm_lead_channel_category
from . import test_crm_lead_sla
from . import test_crm_lead_lost_reason_mandatory
